language: node_js
node_js:
  - '8.10.0'
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
install:
  # First install dependencies of the project itself
  - npm install -D
  - cd tests
  - npm install -D
script:
  - npm run test -- --record
